#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Daniel Rigoberto Jacobo Sandoval
#
# Regenerates THIRD_PARTY_LICENSES.md from go.mod via go-licenses. CI runs
# this and then `git diff --exit-code` on the result: a dependency added
# without regenerating this file fails the build, and so does a dependency
# whose license is copyleft or undetectable.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

GO_LICENSES_VERSION="v1.6.0"
MODULE="$(go list -m)"
OUT="THIRD_PARTY_LICENSES.md"
COPYLEFT_RE='(^|-| )(GPL|AGPL|LGPL|MPL)(-|$| )'

csv="$(go run "github.com/google/go-licenses@${GO_LICENSES_VERSION}" csv ./... 2>/dev/null \
  | grep -v "^${MODULE}," || true)"

{
  echo "# Third-Party Licenses"
  echo
  echo "Generated by \`scripts/gen-third-party.sh\` from \`go.mod\`. Do not edit by hand."
  echo
  if [[ -z "$csv" ]]; then
    echo "No third-party dependencies at this time."
  else
    echo "| Module | License |"
    echo "|---|---|"
    while IFS=',' read -r module _url license; do
      [[ -z "$module" ]] && continue
      echo "| ${module} | ${license} |"
    done <<<"$csv"
  fi
} >"$OUT"

if [[ -n "$csv" ]]; then
  while IFS=',' read -r module _url license; do
    [[ -z "$module" ]] && continue
    if [[ -z "$license" || "$license" == "Unknown" ]]; then
      echo "error: $module has no detectable license" >&2
      exit 1
    fi
    if [[ "$license" =~ $COPYLEFT_RE ]]; then
      echo "error: $module is under a copyleft license ($license), not allowed" >&2
      exit 1
    fi
  done <<<"$csv"
fi

echo "Wrote $OUT"
